modLoader = "javafml" #mandatory
loaderVersion = "[39,)"
license = "All Rights Reserved"
[[mods]] #mandatory
modId = "mightymachines" #mandatory
version = "${file.jarVersion}" #mandatory
displayName = "MightyMachines" #mandatory
authors = "YaBoiChips, VexxJ" #optional
description = '''

'''
[[dependencies.mightymachines]] #optional
modId = "forge"
mandatory = true
versionRange = "[39,)"
ordering = "NONE"
side = "BOTH"
[[dependencies.mightymachines]]
modId = "minecraft"
mandatory = true
versionRange = "[1.18.1,1.19)"
ordering = "NONE"
side = "BOTH"
